### ISSUE TITLE
Tactical Graphics Examples or Documentation

### ISSUE THREAD

**Issue by wallyatkins** [missioncommand/old-mil-sym-java#3]
Are there any additional examples of tactical graphics or documentation on how to render them (in KML or other formats)? So far I have found the range fan KML example in the multiPoints.html but I have not been able to get another graphic (like an Axis of Advance) to work following that example.

**Comment by johnmod3** [comment]
some random notes I had:

http://mapnotes.com/

http://milsym.codeplex.com/

FYI: https://wwhgd.org/ and http://socopgeosemantics2012.eventbrite.com/# ( 5th Annual Spatial Ontology Community (SOCoP) of Practice Workshop: Developing Geo-Spatial Ontologies &Ontology Patterns   Nov. 29-30, 2012 (9-5)  U. S. Geological Survey National Center 12201 }

This forum mentions it: 
http://discussions.sisostds.org/threadview.aspx?fid=31&threadid=49220 

This website has symbols, but not comprehensive and based on the NATO 
standard, which is kinda a subset of 2525C. 
http://www.mapsymbs.com/ 

Here's some.   You should be able to figure it out and iterate to get 
them all. 
http://www.stackframe.com/SymbolFactory/symbols 

This one seems to be the most comprehensive, but I didn't get very far 
as the site doesn't seem to have been maintained since 2006. 
http://home.hiwaay.net/~georgech/Standards/warrior_symbology.htm 

See http://www.stackframe.com/software/Ortelium for information about Ortelium.

See http://www.stackframe.com/SymbolFactory/ for a demo.

See https://github.com/StackFrame/Ortelium/ for the source.

…………………………...
John Scott
AirGap, LLC
john.scott@airgapit.com
240.401.6574

On February 19, 2014 at 10:27:46 AM, Wally Atkins (notifications@github.com) wrote:

Are there any additional examples of tactical graphics or documentation on how to render them (in KML or other formats)? So far I have found the range fan KML example in the multiPoints.html but I have not been able to get another graphic (like an Axis of Advance) to work following that example.

**Comment by wallyatkins** [comment]
Appreciate the notes/links but I was hoping to find API documentation for mil-sym-java. Specifically for tactical graphics rendering.

**Comment by johnmod3** [comment]
maybe ask mil-oss list?

…………………………...
John Scott
AirGap, LLC
john.scott@airgapit.com
240.401.6574

On February 19, 2014 at 12:43:55 PM, Wally Atkins (notifications@github.com) wrote:

Appreciate the notes/links but I was hoping to find API documentation for mil-sym-java. Specifically for tactical graphics rendering.

**Comment by wallyatkins** [comment]
Worth a shot :+1:

**Comment by michael-spinelli** [comment]
We do need to do more work on documentation and samples.  For the java baseline we have our first draft of the developer's guide for using the web service here: 
https://github.com/missioncommand/mil-sym-java/tree/master/documentation

We also have a sample for using the renderer libraries directly here:
https://github.com/missioncommand/mil-sym-java/tree/master/samples/rendering-sample-1

**Comment by mdeutch3** [comment]
The range fan takes only one control point and uses modifier arrays for the left azimuth, right azimuth in degrees, min range and max range in meters.

```
 var symbolCode4 = "GFFPAXS---****X"; //sector range fan



 var controlPoints4 = "66.26700036208742,30.62755038706961";
```

You need to edit the symbol code  and the control points in multiPoints.html. For most of the multipoint symbols you need at least two control points. For an axis of advance symbol remember to include an additional point (somewhere near the 0th point) which establishes the location of the arrowhead as shown in Mil-Std-2525. Assume you’ve placed the mil-sym-service.war in the Tomcat webapps and started Tomcat so that mil-sym-service has deployed. You could edit multiPoints.html as follows:

var symbolCode4="G_GPOLAV--_***X";

var controlPoints4="66.255,30.6 66.45,30.6 66.256,30.61";

var bbox4 = "66.2,30.5,66.5,30.8";

Open test-index.jsp with Firefox browser and click on the MultiPoints Test Page link. When the test page opens click Test Multipoint. You should see the KML content display on the page.

A way to display the resultant KML string on a 3D globe viewer is to copy and paste the above result into a kml file that Google Earth can handle:

<?xml version='1.0' encoding='UTF-8'?>

<kml xmlns='http://www.opengis.net/kml/2.2'>

<Document>

//paste <Folder> [KML string] </Folder> here

</Document>

</kml>

Copy and paste everything within/including the result Folder tags into a kml file between the document tags as shown. Right click on the kml file and open with Google Earth, it should display the symbol. I hope that helps.

Michael Deutch 

SBSI

**Comment by michael-spinelli** [comment]
Updated [multiPoints.html](https://github.com/missioncommand/mil-sym-java/blob/master/service/mil-sym-service/src/main/webapp/multiPoints.html) with more usage samples.  Ambush in KML & JSON as well as Axis of Advance Ground Main.

Also update readme.md to make the documentation more visible.

**Comment by michael-spinelli** [comment]
Join https://groups.google.com/forum/#!forum/mission-command-milstd-renderer
for renderer discussion.
