### ISSUE TITLE
Internal server error with No-Fire Area (NFA) Circular

### ISSUE THREAD

**Issue by murphylemur** [missioncommand/old-mil-sym-java#4]
I am getting an internal server error (Http status 500) when trying to get a No-Fire Area (NFA) Circular graphic.  Below is the url I am using for the graphic:

_renderer/mp3d/G_F_ACNC--_**_X?symbolCode=G_F*ACNC--***_X&controlPoints=-99.240018953102,32.6523830859039&pixelWidth=0&pixelHeight=0&FORMAT=1&SYMSTD=1&scale=1&modifiers={"modifiers":{"AM":[5000]}}_

I have been doing similar graphics such as Fire Support Area (FSA) Circular and it is working fine using the same url but replacing the symbol code. (G_F_ACSC--****X)

**Comment by michael-spinelli** [comment]
Your scale of '1' is too low.  Scale isn't a multiplier.  Scale is a number corresponding to how many meters one meter of the map represents. A value "50000" would mean 1:50K which means for every meter of our map it represents 50000 meters of real world distance.  I think NFA is failing because it's trying to generate the hash line fill for the circular area but the scale of 1 is messing it up.  Also, you don't need to pass pixelWidth or pixelHeight when using the mp3d url.  Those are for mp2d.  Check [the docs](https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#4-using-the-rest-service-for-generating-multipoint-symbology-kml).

We are evaluating if a scale of '1' is something we should support.  Definitely we need to handle it more gracefully than throwing an internal server error.

**Comment by murphylemur** [comment]
OK that makes sense.  We shouldn't be using scale of '1' anyways.

**Comment by michael-spinelli** [comment]
Improved handling of not great scale values.
Code checked in.  New release sometime this week.
