### ISSUE TITLE
Boundaries do not repeat information

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#52]
For both Boundaries and Linear Smoke Targets, the parameters specify that "The line segment between each pair of anchor points will repeat all information associated with the line segment between points 1 and 2." They are currently only rendering on the center-most segment.

![image](https://cloud.githubusercontent.com/assets/7013389/23040783/3bac084e-f458-11e6-8ca5-f8a6cfce9fea.png)

**Comment by mdeutch3** [comment]
That is how we've been directed to display the text for these symbols, it is by design.

**Comment by ChristinaKochan** [comment]
So is the expectation that the user would create multiple individual symbols for each segment in order to get the labels on each segment? I wonder if you know why that decision was made, just so I can explain it to my customer. If not, no worries.

**Comment by mdeutch3** [comment]
For boundaries they have very long lines with sometimes short segments and there was too much text showing so that it obscured the line. Also if the client zooms or pans then the symbol refreshes so the middle segment would always be visible after clipping. Then the text would always be visible. So they didn't need it on every segment.

**Comment by ChristinaKochan** [comment]
Ok, I will communicate this to my customer and if they still need all the labels we can figure it out on our end. Thank you!
