### ISSUE TITLE
ENY label being covered up on some symbols

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#71]
On the following points, the ENY label is being covered up when the Designation text is entered.
(All 3 of these are under the Action Points (General).

- Contact Point
- Decision Point
- Waypoint

The 2525B standard show the "t" modifier in the middle position for both Contact Point and Decision Point. When Designation text is entered, however, the ENY is covered up (not visible)

Contact Point Set to Hostile with a designation value:
![enywithoutdesignation](https://cloud.githubusercontent.com/assets/22623059/25682057/50a81530-301c-11e7-94df-b2230cb32c3e.PNG)

Same point without a designation value:
![designationovereny](https://cloud.githubusercontent.com/assets/22623059/25682064/5776aa98-301c-11e7-944e-064a3066b614.PNG)

For Waypoint, the 2525B shows the "t" modifier in the 3 o'clock position; again, when the Designation text is entered, the ENY is covered up (not visible).

**Comment by michael-spinelli** [comment]
Ok, those symbols don't have an 'N' modifier so I'll make sure "ENY" doesn't show up for them.

**Comment by david-melendez** [comment]
Are you sure about these symbols not having the "N" modifier?  I thought that if a symbol could be made hostile, it should be able to have the "N" modifier so the the "ENY" could be added to symbol for printing on a black and white printer.

**Comment by david-melendez** [comment]
Just checking in on the status of this issue.

**Comment by michael-spinelli** [comment]
The 2525 doesn't say much about it.  The USAS talks about it in the context of rendering.  Printing isn't called out specifically.
For now I'm going to go with the templates and say that since the templates do not indicate placement for an 'N' modifier for these symbols, there isn't one.  I can ask up the line but I'm still waiting for them to get back to me on the METOC graphic so I don't expect that to be fruitful.
